language: python
python:
 - "2.7"
env:
  - DEPLOY=true PULL_REQUEST=$TRAVIS_PULL_REQUEST CMS_BRANCH=$TRAVIS_BRANCH
install:
  - pip install html5validator
  - npm install -g npm
  - npm install -g jshint
  - npm install -g recess
  - npm install -g node
  - npm install -g http-server
  - npm install -g phantomjs
  - npm install -g pa11y
before_script:
  - chmod +x ./.scripts/deploy.sh
script:
  # HTML5 Validation
  - html5validator
  # Javascript validation
  - jshint ./_static/js/*
  # CSS Validation
  - recess ./_static/css/*
  # Accessibility Validation
  - http-server -p 8080 >/dev/null 2>&1 &
  - pa11y localhost:8080/index.html -s WCAG2AAA
after_success:
  - ./.scripts/deploy.sh
